### ISSUE TITLE
Add typing to aliases.py

### ISSUE THREAD

**Issue by dpriskorn** [LeMyst/WikibaseIntegrator#228] opened 2021-09-14 08:06 UTC
https://github.com/LeMyst/WikibaseIntegrator/blob/57fd784b6c7b337ef5c9f4d6c1f569ab36b0f3d5/wikibaseintegrator/models/aliases.py#L21

`-> Union[List[str], None]`?

**Comment by dpriskorn** [comment] 2021-09-14 08:22
It seems this get() does not give back strings.
```
INFO:models.wikidata:entity_id:Q415271
DEBUG:root:here now
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.wikidata.org:443
⠏ Fetching English label and aliases...DEBUG:urllib3.connectionpool:https://www.wikidata.org:443 "POST /w/api.php HTTP/1.1" 200 None
DEBUG:root:aliases from wbi:[<Alias @3082e0 _LanguageValue__language='en' _LanguageValue__value='c-erb B2/neu protein' _LanguageValue__removed=False>, <Alias @308340 _LanguageVa
lue__language='en' _LanguageValue__value='human epidermal growth factor receptor 2' _LanguageValue__removed=False>, <Alias @3083a0 _LanguageValue__language='en' _LanguageValue__
value='tyrosine kinase-type cell surface receptor HER2' _LanguageValue__removed=False>, <Alias @308400 _LanguageValue__language='en' _LanguageValue__value='proto-oncogene Neu' _
LanguageValue__removed=False>, <Alias @308460 _LanguageValue__language='en' _LanguageValue__value='v-erb-b2 erythroblastic leukemia viral oncogene homolog 2, neuro/glioblastoma
derived oncogene homolog' _LanguageValue__removed=False>, <Alias @3084c0 _LanguageValue__language='en' _LanguageValue__value='MLN 19' _LanguageValue__removed=False>, <Alias @308
520 _LanguageValue__language='en' _LanguageValue__value='receptor tyrosine-protein kinase erbB-2' _LanguageValue__removed=False>, <Alias @308580 _LanguageValue__language='en' _L
anguageValue__value='neuroblastoma/glioblastoma derived oncogene homolog' _LanguageValue__removed=False>, <Alias @3085e0 _LanguageValue__language='en' _LanguageValue__value='v-e
rb-b2 avian erythroblastic leukemia viral oncogene homolog 2' _LanguageValue__removed=False>, <Alias @308640 _LanguageValue__language='en' _LanguageValue__value='herstatin' _Lan
guageValue__removed=False>, <Alias @3086a0 _LanguageValue__language='en' _LanguageValue__value='proto-oncogene c-ErbB-2' _LanguageValue__removed=False>, <Alias @308700 _Language
Value__language='en' _LanguageValue__value='v-erb-b2 avian erythroblastic leukemia viral oncoprotein 2' _LanguageValue__removed=False>, <Alias @308760 _LanguageValue__language='
en' _LanguageValue__value='ERBB2' _LanguageValue__removed=False>, <Alias @3087c0 _LanguageValue__language='en' _LanguageValue__value='p185erbB2' _LanguageValue__removed=False>,
<Alias @308820 _LanguageValue__language='en' _LanguageValue__value='metastatic lymph node gene 19 protein' _LanguageValue__removed=False>, <Alias @308880 _LanguageValue__languag
e='en' _LanguageValue__value='neuro/glioblastoma derived oncogene homolog' _LanguageValue__removed=False>, <Alias @3088e0 _LanguageValue__language='en' _LanguageValue__value='Re
ceptor, ErbB-2' _LanguageValue__removed=False>]
```

**Comment by LeMyst** [comment] 2021-09-14 08:34
Hello @dpriskorn 
aliases.get() return a list of LanguageValue. It's by design.
The method can return a list of different language or only one. That's why I can't directly return a string.
LanguageValue implement __str__() method that return the current value.

**Comment by LeMyst** [comment] 2021-09-14 08:38
Typing is on the roadmap, I just wait to have something stable before put type everywhere.

**Comment by LeMyst** [comment] 2021-09-16 20:49
Duplicate of #137

**Closed by LeMyst** 2021-09-16 20:49 UTC
Labels: v0.12+
